name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '15', '16', '17']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test
